[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.8.4"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tower-http = { version = "0.6.2", features = ["cors"] }
tower = "0.4"
jsonwebtoken = "8.3.0"
